# Tommy He <lovenemesis@fedoraproject.org>, 2015. #zanata
# mosquito <sensor.wen@gmail.com>, 2016. #zanata
# cheng ye <18969068329@163.com>, 2017. #zanata
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2018-04-06 07:47+0200\n"
"PO-Revision-Date: 2017-07-24 07:36-0400\n"
"Last-Translator: cheng ye <18969068329@163.com>\n"
"Language-Team: Chinese (China)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: zh-CN\n"
"Plural-Forms: nplurals=1; plural=0\n"
"X-Generator: Zanata 3.9.6\n"

#. Translators: This string is only used in unit tests.
#: ../plugins/system_upgrade.py:38
msgid "the color of the sky"
msgstr ""

#: ../plugins/system_upgrade.py:54
msgid "Need a --releasever greater than the current system version."
msgstr "--releasever 需要大于当前系统版本。"

#. Translators: do not change "reboot" here
#: ../plugins/system_upgrade.py:56
msgid ""
"Download complete! Use 'dnf system-upgrade reboot' to start the upgrade.\n"
"To remove cached metadata and transaction use 'dnf system-upgrade clean'"
msgstr ""

#: ../plugins/system_upgrade.py:59
msgid "Sorry, you need to use 'download --releasever' instead of '--network'"
msgstr "很抱歉，您需要使用 'download --releasever' 代替 '--network' 选项"

#: ../plugins/system_upgrade.py:235
msgid "The following boots appear to contain upgrade logs:"
msgstr "以下引导信息包含升级日志："

#: ../plugins/system_upgrade.py:245
msgid "-- no logs were found --"
msgstr "-- 未发现日志 --"

#: ../plugins/system_upgrade.py:260
msgid "Cannot find logs with this index."
msgstr "无法找到此索引日志。"

#: ../plugins/system_upgrade.py:269
msgid "Unable to match systemd journal entry"
msgstr ""

#: ../plugins/system_upgrade.py:288
msgid "Prepare system for upgrade to a new release"
msgstr "为升级至新发布版本准备系统"

#: ../plugins/system_upgrade.py:298
msgid "keep installed packages if the new release's version is older"
msgstr "如果新发行版的包较旧，则保持已安装软件包"

#: ../plugins/system_upgrade.py:302
msgid "which logs to show"
msgstr ""

#: ../plugins/system_upgrade.py:345
msgid ""
"Before you continue ensure that your system is fully upgraded by running "
"\"dnf --refresh upgrade\". Do you want to continue"
msgstr ""

#: ../plugins/system_upgrade.py:349
msgid "Operation aborted."
msgstr ""

#: ../plugins/system_upgrade.py:400
msgid "system is not ready for upgrade"
msgstr "系统并未准备好升级"

#: ../plugins/system_upgrade.py:402
msgid "upgrade is already scheduled"
msgstr "已计划升级"

#: ../plugins/system_upgrade.py:407
msgid "trigger file does not exist. exiting quietly."
msgstr ""

#: ../plugins/system_upgrade.py:410
msgid "another upgrade tool is running. exiting quietly."
msgstr "另一个升级工具正在运行。默默退出。"

#. Translators: do not change "reboot" here
#: ../plugins/system_upgrade.py:416
msgid "use 'dnf system-upgrade reboot' to begin the upgrade"
msgstr "使用 'dnf system-upgrade reboot' 来开始升级"

#: ../plugins/system_upgrade.py:436
msgid "Rebooting to perform upgrade."
msgstr "重新启动进行升级。"

#: ../plugins/system_upgrade.py:457 ../plugins/system_upgrade.py:463
msgid "Starting system upgrade. This will take a while."
msgstr "正在开始系统升级。这需要一些时间。"

#: ../plugins/system_upgrade.py:489
#, python-format
msgid "Unable to match package: %s"
msgstr ""

#: ../plugins/system_upgrade.py:494
msgid "Unable to match some of packages"
msgstr ""

#: ../plugins/system_upgrade.py:497
msgid "Cleaning up downloaded data..."
msgstr "正在清理已下载的数据…"

#: ../plugins/system_upgrade.py:531
msgid "Download finished."
msgstr "下载完成。"

#: ../plugins/system_upgrade.py:535 ../plugins/system_upgrade.py:536
msgid "Upgrade complete! Cleaning up and rebooting..."
msgstr "升级完成。正在清理并重启…"

#: ../plugins/tracer.py:70
msgid "For more information run:"
msgstr "更多信息请运行："

#: ../plugins/tracer.py:97
msgid "Call to Tracer API ended unexpectedly:"
msgstr "Tracer API 的调用非正常结束："

#: ../plugins/tracer.py:99
msgid ""
"Please visit https://github.com/FrostyX/tracer/issues and submit the issue. "
"Thank you"
msgstr "请访问https://github.com/FrostyX/tracer/issues 并提交此错误。谢谢"

#: ../plugins/tracer.py:101
msgid "We apologize for any inconvenience"
msgstr "为给您带来的不便感到抱歉"

#: ../plugins/rpm_conf.py:69
msgid "Adding '{}' to list of handling packages for rpmconf"
msgstr "正在添加 '{}' 至需要 rpmconf 处理的软件包列表"

#: ../plugins/rpm_conf.py:75
msgid "rpmconf plugin will not run in non-interactive mode"
msgstr "rpmconf 插件不在非交互模式下运行"

#: ../plugins/rpm_conf.py:88
msgid "ignoring sys.exit from rpmconf due to missing MERGE variable"
msgstr "由于缺失MERGE 变量， 忽略rpmconf 的sys.exit"

#: ../plugins/rpm_conf.py:92
msgid "ignoring sys.exit from rpmconf due to missing file"
msgstr "由于缺失文件， 忽略rpmconf 的sys.exit"

#: ../plugins/snapper.py:49
#, python-format
msgid "connect to snapperd failed: %s"
msgstr "连接到 snapperd 失败：%s"

#: ../plugins/snapper.py:55
msgid "creating pre_snapshot"
msgstr ""

#: ../plugins/snapper.py:61
#, python-format
msgid "created pre_snapshot %d"
msgstr ""

#: ../plugins/snapper.py:65
#, python-format
msgid "creating pre_snapshot failed: %s"
msgstr ""

#: ../plugins/snapper.py:71
msgid "skipping post_snapshot because creation of pre_snapshot failed"
msgstr ""

#: ../plugins/snapper.py:77
msgid "creating post_snapshot"
msgstr ""

#: ../plugins/snapper.py:82
#, python-format
msgid "created post_snapshot %d"
msgstr ""

#: ../plugins/snapper.py:86
#, python-format
msgid "creating post_snapshot failed: %s"
msgstr ""

#: ../plugins/kickstart.py:59
msgid "Install packages defined in a kickstart file on your system"
msgstr "在系统中安装 kickstart 文件中定义的软件包"

#: ../plugins/kickstart.py:64
msgid "kickstart file"
msgstr "Kickstart 文件"

#: ../plugins/kickstart.py:82
#, python-format
msgid "file cannot be parsed: %s"
msgstr "文件不能被解析： %s"

#: ../plugins/kickstart.py:99
#, python-format
msgid "No package %s available."
msgstr "无可用软件包 %s。"

#: ../plugins/kickstart.py:104
msgid "Nothing to do."
msgstr "无需任何处理。"

#: ../plugins/torproxy.py:32
msgid "Disabling torproxy plugin: cannot connect to the Tor network"
msgstr "禁用 torproxy 插件：无法连接到Tor 网络"
